spring.application.name=Fish_Waste_Recycle_System1

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/fish_waste_rdb
spring.datasource.username=root
spring.datasource.password=Pass@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update

# Show SQL Queries
spring.jpa.show-sql=true

# Format SQL Queries
spring.jpa.properties.hibernate.format_sql=true

# MySQL Dialect (optional in newer Spring Boot versions)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.tomcat.context-path=/api